# Generated by Django 4.1.2 on 2022-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Электронная почта'),
        ),
    ]
